---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: kube-znn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-znn
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 30
  metrics:
    - type: Pods
      pods:
        metric:
          name: request_duration_seconds_average
        target:
          type: AverageValue
          averageValue: "100m"
