apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- prometheus/deployment.yaml
- prometheus/service.yaml
- metrics-server/deployment.yaml
- kube-state-metrics/deployment.yaml
- nginxc-ingress/deployment.yaml
- nginxc-ingress/service.yaml
